name: greet_user
on: push
jobs: 
  greet-user-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat greetings.txt)"
