name: Update README

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script to update README
        run: |
          python update_readme.py  # Replace with your script name if different

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_PAT_SECRET }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update README via GitHub Action"
          git push origin main
